export const DRAFTING_SUGGESTED_PROMPTS = [
  "Draft an employment contract for a software engineer in Bangalore.",
  "Create a rental agreement for a furnished apartment in Delhi.",
  "Generate a sale deed for agricultural land in Maharashtra.",
  "Prepare a non-disclosure agreement between two startups.",
  "Write a power of attorney for property management.",
  "Draft a mutual divorce petition for a couple residing in Chennai.",
  "Create an affidavit for change of name after marriage.",
  "Generate a partnership deed for a new retail business.",
  "Prepare a legal notice for cheque bounce under Section 138.",
  "Write a will for distribution of assets among three children.",
  "Draft a memorandum of understanding (MOU) for a joint venture.",
  "Create a leave and license agreement for a commercial shop in Pune.",
  "Generate a consumer complaint for defective mobile phone purchase.",
  "Prepare a bail application for an accused in a theft case.",
  "Write an indemnity bond for lost share certificates.",
  "Draft a succession certificate application for bank accounts.",
  "Create a legal notice for recovery of unpaid rent.",
  "Generate a loan agreement between friends with repayment terms.",
  "Prepare an affidavit for proof of address for passport application.",
  "Write a deed of gift for a residential property.",
  "Draft a public interest litigation (PIL) for environmental protection.",
  "Create a service agreement for freelance graphic designer.",
  "Generate a legal notice for breach of contract in supply of goods.",
  "Prepare a trust deed for a charitable trust.",
  "Write a judicial affidavit for evidence submission in court.",
  "Draft a family settlement agreement for ancestral property.",
  "Create a vendor agreement for procurement of office supplies.",
  "Generate a franchise agreement for a food business.",
  "Prepare a rent escalation letter for commercial premises.",
  "Write a notice to vacate rented premises within 30 days.",
  "Draft a lease agreement for industrial warehouse space in Hyderabad.",
  "Create a consultancy agreement for IT services with payment milestones.",
  "Generate a notice for termination of employment due to misconduct.",
  "Prepare a settlement agreement for a workplace dispute.",
  "Write a general power of attorney for financial transactions.",
  "Draft a share purchase agreement for a private limited company.",
  "Create an affidavit for income proof for educational loan.",
  "Generate a complaint to the police for lost passport.",
  "Prepare a no objection certificate (NOC) for vehicle sale.",
  "Write a deed of relinquishment for ancestral property rights.",
  "Draft a maintenance petition under Section 125 CrPC.",
  "Create a legal notice for delay in possession of flat by builder.",
  "Generate a confidentiality agreement for research collaboration.",
  "Prepare a complaint under the Domestic Violence Act.",
  "Write a commercial sub-lease agreement for office space.",
  "Draft a declaration for single marital status.",
  "Create a deed of hypothecation for securing a business loan.",
  "Generate an agreement for sale of movable assets.",
  "Prepare a petition for grant of guardianship of a minor.",
  "Write a letter of intent (LOI) for business acquisition.",
  "Draft a co-founder agreement for a startup.",
  "Create a retainer agreement for legal consultancy services.",
  "Generate a complaint to RERA for delay in property possession.",
  "Prepare a notice for non-renewal of lease.",
  "Write an affidavit for correction of date of birth in official records.",
  "Draft a deed of partition for joint family property.",
  "Create a leave of absence letter for medical reasons.",
  "Generate a petition for quashing of FIR.",
  "Prepare a vendor termination notice for breach of service.",
  "Write a board resolution for opening a company bank account.",
  "Draft a consultancy retainer agreement for a law firm.",
  "Create a marriage registration application for a Hindu couple.",
  "Generate an affidavit for lost educational certificates.",
  "Prepare a complaint to the Consumer Forum for faulty home appliances.",
  "Write a notice for early termination of rental agreement by tenant.",
  "Draft a deed of adoption for a minor child.",
  "Create a letter of authorization for collecting documents.",
  "Generate a partnership dissolution agreement.",
  "Prepare a complaint under Section 498A for cruelty by husband.",
  "Write a declaration for non-involvement in criminal cases.",
  "Draft a vendor onboarding agreement for an e-commerce platform.",
  "Create a power of attorney for vehicle sale and transfer.",
  "Generate an agreement for freelance content writing services.",
  "Prepare a petition for restoration of conjugal rights.",
  "Write a legal notice for non-payment of maintenance charges.",
  "Draft a declaration of solvency for company liquidation.",
  "Create a complaint to the Lokayukta for corruption.",
  "Generate a notice for encroachment on private property.",
  "Prepare a deed of release for mortgage property.",
  "Write an affidavit for single parent status for school admission.",
  "Draft a tripartite agreement for property development.",
  "Create a non-compete agreement for departing employee.",
  "Generate a petition for change of guardianship.",
  "Prepare a declaration of gift for movable property.",
  "Write a complaint to the police for cybercrime incident.",
  "Draft a letter of indemnity for lost insurance policy.",
  "Create a notice for increase in maintenance charges by society.",
  "Generate a settlement deed for marital dispute.",
  "Prepare a complaint to the Human Rights Commission.",
  "Write an agreement for sale of intellectual property rights.",
  "Draft a memorandum of association for a Section 8 company.",
  "Create a complaint to the Banking Ombudsman for unauthorized transaction.",
  "Generate a deed of assignment for trademark rights.",
  "Prepare a legal notice for copyright infringement.",
  "Write an affidavit for lost PAN card.",
  "Draft a notice for recovery of security deposit from landlord.",
  "Create a service level agreement (SLA) for IT support services.",
  "Generate a complaint to the State Consumer Commission for medical negligence.",
  "Prepare a declaration for Hindu Undivided Family (HUF) creation.",
  "Write a deed of rectification for correcting errors in property documents.",
  "Draft a petition for anticipatory bail in a criminal case.",
  "Create a notice for non-payment of society maintenance charges.",
  "Generate a letter of guarantee for business loan.",
  "Prepare a complaint to the Information Commission under RTI Act.",
  "Write a declaration for self-attestation of documents.",
  "Draft a complaint to the Labour Commissioner for unfair dismissal.",
  "Create a non-solicitation agreement for ex-employees.",
  "Generate a deed of surrender of tenancy rights.",
  "Prepare an affidavit for income tax exemption under Section 80G.",
  "Write a notice for encroachment removal from public land.",
  "Draft a vendor agreement for event management services.",
  "Create a complaint for harassment at workplace.",
  "Generate a declaration for minority status for educational institution.",
  "Prepare a legal notice for defamation.",
  "Write a petition for transfer of case to another court.",
  "Draft a deed of guarantee for personal loan.",
  "Create an agreement for joint development of real estate property.",
  "Generate a complaint to the Competition Commission of India.",
  "Prepare a notice for non-renewal of employment contract.",
  "Write a declaration of export of goods for customs clearance.",
  "Draft a deed of assignment for copyright in literary works.",
  "Create a legal notice for non-payment of professional fees.",
  "Generate a complaint to the Insurance Ombudsman for claim rejection.",
  "Prepare a declaration for self-occupation of house property.",
  "Write a will specifically for movable assets.",
  "Draft a letter of consent for minor's travel abroad.",
  "Create a complaint to the Bar Council for professional misconduct.",
  "Generate an agreement for co-working space sharing.",
  "Prepare a deed of exchange for agricultural land.",
  "Write an affidavit for non-receipt of goods.",
  "Draft a legal notice for infringement of design rights.",
  "Create a petition for restoration of company name under Companies Act.",
  "Generate a declaration for non-encumbrance of property.",
  "Prepare a complaint to the Medical Council for negligence.",
  "Write a deed of rectification for mutual mistake in contract.",
  "Draft an agreement for transfer of tenancy rights.",
  "Create a legal notice for wrongful termination of dealership.",
  "Generate a declaration for change of religion.",
  "Prepare a complaint to the Cyber Appellate Tribunal.",
  "Write an affidavit for proof of relationship for visa application.",
  "Draft a tripartite escrow agreement for property sale.",
  "Create an agreement for supply of goods on credit.",
  "Generate a petition for maintenance of senior citizens.",
  "Prepare a legal notice for violation of privacy.",
  "Write a declaration of intent to marry under Special Marriage Act.",
  "Draft a deed of mortgage for securing a housing loan.",
  "Create a complaint to the District Magistrate for illegal construction.",
  "Generate a letter of undertaking for export compliance.",
  "Prepare a non-disclosure and non-circumvention agreement.",
  "Write a notice for revocation of power of attorney.",
  "Draft a deed of release for relinquishing inheritance rights.",
  "Create a complaint to the Registrar of Societies for mismanagement.",
  "Generate a legal notice for non-delivery of online order.",
  "Prepare a declaration for agricultural income for tax purposes.",
  "Write a letter of authorization for bank account operations.",
  "Draft a deed of assignment for patent rights.",
  "Create a complaint to the Registrar of Companies for non-compliance.",
  "Generate a notice for delay in payment to contractor.",
  "Prepare a declaration for self-employment status.",
  "Write an affidavit for correction of name in birth certificate.",
  "Draft a legal notice for encroachment on agricultural land.",
  "Create a tripartite agreement for loan disbursement.",
  "Generate a complaint to the Telecom Regulatory Authority for service issues.",
  "Prepare a declaration for dependent family members for insurance.",
  "Write a deed of indemnity for property transaction.",
  "Draft a non-disclosure agreement for startup investors.",
  "Create a complaint to the Municipal Corporation for illegal construction.",
  "Generate a letter of intent for franchise purchase.",
  "Prepare a declaration for non-possession of PAN card.",
  "Write a legal notice for violation of lease terms.",
  "Draft a service agreement for annual maintenance contract (AMC).",
  "Create a complaint to the Election Commission for voter list errors.",
  "Generate a declaration for foreign remittance under FEMA.",
  "Prepare a deed of guarantee for business partnership.",
  "Write an affidavit for proof of residence for school admission.",
  "Draft a complaint to the State Human Rights Commission for police excess.",
  "Create a legal notice for violation of intellectual property rights.",
  "Generate a declaration for GST registration.",
  "Prepare a deed of assignment for leasehold rights.",
  "Write a notice for non-renewal of franchise agreement.",
  "Draft a legal notice for violation of non-compete clause.",
  "Create a complaint to the State Commission for Women regarding harassment.",
  "Generate a deed of family arrangement for division of property.",
  "Prepare a declaration for non-conviction for government job application.",
  "Write an affidavit for proof of income for scholarship application.",
  "Draft a service agreement for housekeeping services in a housing society.",
  "Create a complaint to the Income Tax Department for PAN misuse.",
  "Generate a letter of authorization for GST filing.",
  "Prepare a deed of assignment for film distribution rights.",
  "Write a notice for delay in delivery of construction materials.",
  "Draft a declaration for single ownership of business.",
  "Create a complaint to the Railway Claims Tribunal for lost luggage.",
  "Generate a legal notice for breach of warranty in product sale.",
  "Prepare an affidavit for correction of father's name in school records.",
  "Write a deed of hypothecation for vehicle loan.",
  "Draft a memorandum of settlement for industrial dispute.",
  "Create a letter of undertaking for customs clearance.",
  "Generate a declaration for non-encumbrance on vehicle.",
  "Prepare a complaint to the State Pollution Control Board for air pollution.",
  "Write a notice for cancellation of event management contract.",
  "Draft a legal notice for non-payment of consultancy charges.",
  "Create a deed of assignment for music publishing rights.",
  "Generate a declaration of assets for election nomination.",
  "Prepare an affidavit for proof of relationship for dependent visa.",
  "Write a complaint to the District Consumer Forum for delay in service.",
  "Draft a vendor agreement for catering services.",
  "Create a notice for non-renewal of dealership agreement.",
  "Generate a declaration for self-attestation of mark sheets.",
  "Prepare a deed of guarantee for educational loan.",
  "Write a legal notice for violation of terms in a joint venture agreement.",
  "Draft a deed of assignment for software development rights.",
  "Create a complaint to the State Electricity Board for faulty billing.",
  "Generate a declaration for non-receipt of refund from online retailer.",
  "Prepare a legal notice for unauthorized use of trade name.",
  "Write an affidavit for correction of address in Aadhaar card.",
  "Draft a service agreement for digital marketing services.",
  "Create a complaint to the State Transport Authority for permit issues.",
  "Generate a deed of pledge for securing a gold loan.",
  "Prepare a notice for delay in payment of professional fees.",
  "Write a declaration for loss of original property documents.",
  "Draft a tripartite agreement for equipment leasing.",
  "Create a legal notice for violation of advertising standards.",
  "Generate a complaint to the Food Safety Authority for adulteration.",
  "Prepare a declaration for non-receipt of dividend from company.",
  "Write a deed of assignment for broadcasting rights.",
  "Draft an agreement for joint authorship of a book.",
  "Create a complaint to the Registrar of Trademarks for opposition.",
  "Generate a legal notice for delay in possession of commercial property.",
  "Prepare an affidavit for proof of minority for educational benefits.",
  "Write a declaration for self-attestation of income certificate.",
  "Draft a service agreement for security agency services.",
  "Create a complaint to the District Education Officer for school fee hike.",
  "Generate a deed of assignment for distribution rights in India.",
  "Prepare a notice for breach of confidentiality agreement.",
  "Write an affidavit for proof of relationship for medical insurance.",
  "Draft a legal notice for unauthorized subletting of premises.",
  "Create a complaint to the Real Estate Regulatory Authority for project delay.",
  "Generate a declaration for non-possession of ration card.",
  "Prepare a deed of release for relinquishing partnership interest.",
  "Write a letter of undertaking for timely completion of project.",
  "Draft a legal notice for unauthorized construction on adjacent property.",
  "Create a complaint to the Registrar of Births and Deaths for delayed registration.",
  "Generate a deed of assignment for mobile app intellectual property.",
  "Prepare a declaration for non-possession of driving license.",
  "Write an affidavit for correction of gender in official records.",
  "Draft a service agreement for pest control services in a housing society.",
  "Create a complaint to the District Legal Services Authority for denial of legal aid.",
  "Generate a notice for breach of data protection agreement.",
  "Prepare a deed of assignment for franchise rights.",
  "Write a declaration for foreign inward remittance for RBI compliance.",
  "Draft a legal notice for non-payment of security services invoice.",
  "Create a complaint to the State Consumer Disputes Redressal Commission for defective furniture.",
  "Generate a deed of release for relinquishing claim in insurance policy.",
  "Prepare a declaration for self-attestation of caste certificate.",
  "Write an affidavit for proof of relationship for government benefits.",
  "Draft a memorandum of understanding for academic collaboration.",
  "Create a legal notice for violation of advertising agreement.",
  "Generate a complaint to the State Human Rights Commission for denial of basic amenities.",
  "Prepare a deed of assignment for publishing rights of a book.",
  "Write a declaration for non-receipt of pension.",
  "Draft a service agreement for logistics and supply chain management.",
  "Create a complaint to the State Bar Council for non-compliance by advocate.",
  "Generate a notice for breach of exclusivity clause in distribution agreement.",
  "Prepare a deed of assignment for royalty rights in music.",
  "Write a declaration for non-possession of voter ID card.",
  "Draft a legal notice for violation of non-solicitation agreement.",
  "Create a complaint to the District Magistrate for illegal mining.",
  "Generate a deed of assignment for agency rights.",
  "Prepare a declaration for self-attestation of disability certificate.",
  "Write an affidavit for proof of residence for LPG connection.",
  "Draft a legal notice for unauthorized use of company logo.",
  "Create a complaint to the District Registrar for delay in property registration.",
  "Generate a deed of assignment for film remake rights.",
  "Prepare a declaration for non-possession of passport.",
  "Write an affidavit for correction of mother's name in official documents.",
  "Draft a service agreement for cloud storage services.",
  "Create a complaint to the State Medical Council for unethical practice.",
  "Generate a notice for breach of payment terms in supply agreement.",
  "Prepare a deed of assignment for translation rights of a book.",
  "Write a declaration for non-possession of marriage certificate.",
  "Draft a legal notice for violation of employee confidentiality agreement.",
  "Create a complaint to the District Consumer Forum for faulty electronics.",
  "Generate a deed of release for relinquishing claim in joint venture.",
  "Prepare a declaration for self-attestation of residence certificate.",
  "Write an affidavit for proof of relationship for dependent pension.",
  "Draft a memorandum of understanding for joint research project.",
  "Create a legal notice for violation of service agreement.",
  "Generate a complaint to the State Commission for Protection of Child Rights.",
  "Prepare a deed of assignment for merchandising rights.",
  "Write a declaration for non-receipt of scholarship amount.",
  "Draft a service agreement for website development.",
  "Create a complaint to the District Magistrate for noise pollution.",
  "Generate a notice for breach of exclusivity agreement.",
  "Prepare a deed of assignment for mobile game rights.",
  "Write a declaration for non-possession of birth certificate.",
  "Draft a legal notice for violation of advertising partnership terms.",
  "Create a complaint to the State Bar Council for delay in case handling.",
  "Generate a deed of release for relinquishing claim in partnership firm.",
  "Prepare a declaration for self-attestation of income tax return.",
  "Write an affidavit for proof of residence for government subsidy."
];