export const SUGGESTED_PROMPTS_BY_AREA = {
  ACCIDENTS_AND_TRAFFIC: [
    "What to do when you are involved in a car accident?",
    "What to do when you receive a traffic ticket?",
    "What to do when you are involved in a personal injury lawsuit?",
    "What to do when you are dealing with a medical malpractice case?",
    "What to do when you are involved in a workplace injury?",
  ],
  
  DEBT_AND_FINANCIAL: [
    "What to do when you are sued for debt?",
    "What to do when you need to file for bankruptcy?",
    "What to do when you are facing a foreclosure?",
    "What to do when you are facing a lawsuit from a creditor?",
    "What to do when you are dealing with a credit report error?",
    "What to do when you are involved in a dispute over a business loan?",
  ],
  
  CRIMINAL_AND_LEGAL_PROCEEDINGS: [
    "What to do when you are accused of a crime?",
    "What to do when you are dealing with a breach of contract?",
    "What to do when you are involved in a contract dispute?",
    "What to do when you are dealing with a will or estate dispute?",
    "What to do when you are creating a will?",
    "What to do when you are establishing a trust?",
    "What to do when you are dealing with a power of attorney issue?",
  ],
  
  EMPLOYMENT_AND_WORKPLACE: [
    "What to do when you are denied unemployment benefits?",
    "What to do when you are experiencing harassment at work?",
    "What to do when you are fired without cause?",
    "What to do when you are facing a lawsuit from a former employee?",
    "What to do when you are dealing with a workers' compensation claim?",
    "What to do when you are dealing with a pension plan issue?",
    "What to do when you are involved in a dispute over a retirement account?",
  ],
  
  HOUSING_AND_REAL_ESTATE: [
    "What to do when you are facing eviction?",
    "What to do when you are dealing with a difficult landlord?",
    "What to do when you are buying a house?",
    "What to do when you are selling a house?",
    "What to do when you are involved in a real estate dispute?",
    "What to do when you are dealing with a neighbor dispute?",
    "What to do when you are involved in a dispute over property boundaries?",
    "What to do when you are dealing with a noise complaint from a neighbor?",
    "What to do when you are involved in a dispute over a shared driveway?",
    "What to do when you are dealing with a problem with a home improvement contractor?",
    "What to do when you are involved in a dispute over a timeshare?",
    "What to do when you are dealing with a vacation rental issue?",
    "What to do when you are dealing with a zoning issue?",
  ],
  
  FAMILY_LAW: [
    "What to do when you are considering divorce?",
    "What to do when you are seeking custody of a child?",
    "What to do when you are dealing with a child support issue?",
  ],
  
  BUSINESS_AND_CORPORATE: [
    "What to do when you are involved in a business partnership dispute?",
    "What to do when you are starting a new business?",
    "What to do when you are involved in a dispute over a business merger?",
    "What to do when you are dealing with a hostile takeover?",
    "What to do when you are involved in a dispute over a non-compete agreement?",
    "What to do when you are involved in a dispute over a manufacturing contract?",
    "What to do when you are dealing with a supply chain management issue?",
    "What to do when you are involved in a dispute over a logistics and transportation contract?",
    "What to do when you are dealing with a call center outsourcing issue?",
    "What to do when you are involved in a dispute over a business process outsourcing (BPO) contract?",
    "What to do when you are dealing with a managed service provider (MSP) contract issue?",
  ],
  
  INTELLECTUAL_PROPERTY: [
    "What to do when you are dealing with intellectual property issues?",
    "What to do when you are dealing with a trade secret issue?",
    "What to do when you are involved in a dispute over a trademark?",
    "What to do when you are dealing with a copyright infringement issue?",
    "What to do when you are involved in a dispute over a patent?",
    "What to do when you are dealing with a biotechnology patent issue?",
    "What to do when you are involved in a dispute over a pharmaceutical patent?",
    "What to do when you are dealing with a medical device patent issue?",
  ],
  
  TECHNOLOGY_AND_CYBER: [
    "What to do when you are dealing with a data breach?",
    "What to do when you are involved in a dispute over cybersecurity?",
    "What to do when you are dealing with a ransomware attack?",
    "What to do when you are involved in a dispute over online defamation?",
    "What to do when you are dealing with a social media harassment issue?",
    "What to do when you are involved in a dispute over a domain name?",
    "What to do when you are dealing with a website accessibility issue?",
    "What to do when you are involved in a dispute over a software development contract?",
    "What to do when you are dealing with a cloud computing contract issue?",
    "What to do when you are involved in a dispute over a technology licensing agreement?",
    "What to do when you are dealing with a cybersecurity insurance issue?",
    "What to do when you are involved in a dispute over a data storage contract?",
    "What to do when you are dealing with a cloud data security issue?",
    "What to do when you are involved in a dispute over a software as a service (SaaS) contract?",
    "What to do when you are dealing with a platform as a service (PaaS) contract issue?",
    "What to do when you are involved in a dispute over an infrastructure as a service (IaaS) contract?",
  ],
  
  CONSUMER_PROTECTION: [
    "What to do when you are involved in a consumer protection issue?",
    "What to do when you are dealing with a product liability issue?",
    "What to do when you are involved in a dispute over a product recall?",
    "What to do when you are dealing with a consumer protection class action?",
  ],
  
  HEALTHCARE_AND_INSURANCE: [
    "What to do when you are involved in a dispute over a healthcare contract?",
    "What to do when you are dealing with a medical billing issue?",
    "What to do when you are involved in a dispute over a health insurance claim?",
    "What to do when you are dealing with a denied health insurance claim?",
    "What to do when you are involved in a dispute over a life insurance policy?",
    "What to do when you are dealing with a disability insurance issue?",
  ],
  
  GOVERNMENT_AND_BENEFITS: [
    "What to do when you are dealing with a veterans' benefits issue?",
    "What to do when you are involved in a dispute over a social security benefits claim?",
  ],
  
  TAX_AND_FINANCIAL_SERVICES: [
    "What to do when you are facing a tax audit?",
    "What to do when you are dealing with a tax lien issue?",
    "What to do when you are involved in a dispute over a property tax assessment?",
    "What to do when you are dealing with a sales tax audit?",
    "What to do when you are involved in a dispute over a use tax issue?",
    "What to do when you are dealing with a customs duty issue?",
    "What to do when you are involved in a dispute over an import/export regulation?",
    "What to do when you are involved in a dispute over a securities fraud claim?",
    "What to do when you are dealing with a stockbroker negligence issue?",
    "What to do when you are involved in a dispute over a financial advisor's conduct?",
    "What to do when you are dealing with a cryptocurrency investment issue?",
    "What to do when you are involved in a dispute over a blockchain technology contract?",
  ],

  // New categories from the provided text files
  GENERAL_LEGAL_QUESTIONS: [
    "What are my rights if I am arrested?",
    "How do I file for divorce?",
    "What is the process for creating a will?",
    "What are the legal requirements for starting a business?",
    "How do I apply for bankruptcy?",
    "What are the steps to sue someone?",
    "What is the difference between a felony and a misdemeanor?",
    "How do I expunge a criminal record?",
    "What are the legal grounds for eviction?",
    "How do I apply for a restraining order?",
    "What are my rights as a tenant?",
    "What are my rights as a landlord?",
    "How do I handle a traffic ticket?",
    "What is the process for adopting a child?",
    "What are the legal implications of co-signing a loan?",
    "How do I contest a will?",
    "What are the steps to file a personal injury claim?",
    "What is the statute of limitations for filing a lawsuit?",
    "How do I protect my intellectual property?",
    "What are the legal requirements for getting married?",
    "How do I change my name legally?",
    "What are the legal consequences of defaulting on a loan?",
    "How do I handle a small claims court case?",
    "What are the legal requirements for a prenuptial agreement?",
    "How do I report workplace discrimination?",
    "What are my rights as an employee?",
    "What are my rights as an employer?",
    "How do I handle a wrongful termination case?",
    "What are the legal requirements for a power of attorney?",
    "How do I handle a child custody dispute?",
    "What are the legal implications of a verbal contract?",
    "How do I handle identity theft?",
    "What are the legal requirements for a lease agreement?",
    "What are my rights during a police search?",
    "How do I dispute a credit report error legally?",
    "What are the legal steps to immigrate to another country?",
    "How do I appeal a court decision?",
    "What are the legal requirements for child support payments?",
    "How do I legally terminate a contract?",
    "What are the consequences of breaking a lease agreement?",
    "How do I file a complaint against a healthcare provider?",
    "What are the legal protections against harassment at work?",
    "How do I legally dissolve a partnership in business?",
    "What are the legal requirements for guardianship of a minor?",
    "How do I handle defamation or slander cases?",
    "What are the penalties for driving under the influence (DUI)?",
    "How do I legally transfer property ownership?",
    "What are my rights as a consumer in product disputes?",
    "How do I handle a breach of contract case?",
    "What are the legal steps to contest traffic violations?",
  ],

  LEGAL_CHARGES: [
    "What are the charges for speeding?",
    "What are the charges for jaywalking?",
    "What are the charges for littering in public areas?",
    "What are the charges for public intoxication?",
    "What are the charges for trespassing on private property?",
    "What are the charges for shoplifting or petty theft?",
    "What are the charges for driving under the influence (DUI)?",
    "What are the charges for possession of illegal drugs?",
    "What are the charges for assault and battery?",
    "What are the charges for domestic violence?",
    "What are the charges for stalking or harassment?",
    "What are the charges for vandalism or criminal mischief?",
    "What are the charges for disorderly conduct in public places?",
    "What are the charges for resisting arrest?",
    "What are the charges for carrying a concealed weapon without a permit?",
    "What are the charges for fraud or identity theft?",
    "What are the charges for tax evasion or tax fraud?",
    "What are the charges for embezzlement or financial crimes?",
    "What are the charges for burglary or breaking and entering?",
    "What are the charges for robbery or armed robbery?",
    "What are the charges for murder or manslaughter?",
    "What are the charges for kidnapping or abduction?",
    "What are the charges for arson or setting fires intentionally?",
    "What are the charges for sexual assault or rape?",
    "What are the charges for child abuse or neglect?",
    "What are the charges for animal cruelty or neglect?",
    "What are the charges for illegal gambling activities?",
    "What are the charges for money laundering or financial schemes?",
    "What are the charges for cybercrime, such as hacking or phishing scams?",
    "What are the charges for contempt of court during legal proceedings?",
    "What are the charges for violating a restraining order?",
    "What are the charges for failing to appear in court when summoned?",
    "What are the charges for perjury or lying under oath?",
    "What are the charges for obstruction of justice?",
    "What are the charges for bribery or corruption?",
    "What are the charges for forgery or counterfeiting documents?",
    "What are the charges for theft by deception or false pretenses?",
    "What are the charges for unauthorized use of a vehicle?",
    "What are the charges for reckless endangerment?",
    "What are the charges for negligent homicide?",
    "What are the charges for involuntary manslaughter?",
    "What are the charges for voluntary manslaughter?",
    "What are the charges for vehicular manslaughter?",
    "What are the charges for hit-and-run accidents?",
    "What are the charges for driving with a suspended license?",
    "What are the charges for reckless driving or aggressive driving?",
    "What are the charges for leaving the scene of an accident?",
    "What are the charges for tampering with evidence?",
    "What are the charges for witness intimidation?",
    "What are the charges for making false police reports?",
  ],

  FILING_COMPLAINTS: [
    "How do I file a complaint against a company for violating consumer protection laws?",
    "How do I file a complaint against a healthcare provider for medical malpractice?",
    "How do I file a complaint against a financial institution for unfair practices?",
    "How do I file a complaint against a real estate agent for misrepresentation?",
    "How do I file a complaint against a government agency for administrative errors?",
    "How do I file a complaint against a school or educational institution for negligence?",
    "How do I file a complaint against a transportation company for accidents or injuries?",
    "How do I file a complaint against a utility company for service disruptions?",
    "How do I file a complaint against a telecommunications provider for poor service?",
    "How do I file a complaint against a food manufacturer for contamination or foodborne illness?",
    "How do I file a complaint against a pharmaceutical company for harm caused by a medication?",
    "How do I file a complaint against a construction company for defects in workmanship?",
    "How do I file a complaint against a company for violating employment laws?",
    "How do I file a complaint against a landlord for violating tenant rights?",
    "How do I file a complaint against a tenant for violating lease terms?",
    "How do I file a complaint against a contractor for poor work quality?",
    "How do I file a complaint against a supplier for defective products?",
    "How do I file a complaint against a distributor for unfair business practices?",
    "How do I file a complaint against a franchisee for violating franchise agreements?",
    "How do I file a complaint against a franchisor for deceptive practices?",
    "How do I file a complaint against a shareholder for violating corporate governance rules?",
    "How do I file a complaint against a director for breach of fiduciary duty?",
    "How do I file a complaint against a creditor for harassment or unfair debt collection?",
    "How do I file a complaint against a debtor for failing to pay debts?",
    "How do I file a complaint against a policyholder for insurance fraud?",
    "How do I file a complaint against an insurer for denying claims unfairly?",
    "How do I file a complaint against a beneficiary for misusing trust funds?",
    "How do I file a complaint against a trustee for mismanaging a trust?",
    "How do I file a complaint against a securities broker for misconduct?",
    "How do I file a complaint against an investment advisor for breach of fiduciary duty?",
    "How do I file a complaint against a financial advisor for providing poor advice?",
    "How do I file a complaint against a bank for violating banking regulations?",
    "How do I file a complaint against a credit card company for unfair practices?",
    "How do I file a complaint against a loan officer for predatory lending practices?",
    "How do I file a complaint against a mortgage broker for deceptive practices?",
    "How do I file a complaint against a property appraiser for inaccurate valuations?",
    "How do I file a complaint against a real estate appraiser for unethical practices?",
    "How do I file a complaint against a home inspector for failing to disclose defects?",
    "How do I file a complaint against a title company for errors in title searches?",
    "How do I file a complaint against an escrow company for mishandling funds?",
    "How do I file a complaint against a notary public for misconduct?",
    "How do I file a complaint against an attorney for professional misconduct?",
    "How do I file a complaint against a judge for judicial misconduct?",
    "How do I file a complaint against a court clerk for administrative errors?",
    "How do I file a complaint against a bail bondsman for unethical practices?",
    "How do I file a complaint against a private investigator for invasion of privacy?",
    "How do I file a complaint against a process server for improper service of documents?",
    "How do I file a complaint against a collection agency for harassment?",
    "How do I file a complaint against a credit reporting agency for errors in credit reports?",
    "How do I file a complaint against a debt collector for violating debt collection laws?",
  ],

  LEGAL_SYSTEM_AND_PROCESSES: [
    "How do legal systems protect intellectual property rights?",
    "How do legal contracts ensure confidentiality and non-disclosure?",
    "How do legal precedents influence court decisions in similar cases?",
    "How do legal frameworks regulate international trade agreements?",
    "How do legal professionals handle conflicts of interest in client representation?",
    "How do legal documents, such as wills, ensure estate distribution according to the deceased's wishes?",
    "How do legal processes for divorce differ across various jurisdictions?",
    "How do legal rights of tenants protect them from unfair eviction practices?",
    "How do legal obligations of landlords ensure property maintenance and safety?",
    "How do legal systems address cybercrime and online fraud effectively?",
    "How do legal procedures for filing a lawsuit against a government agency work?",
    "How do legal protections for whistleblowers prevent retaliation in the workplace?",
    "How do legal requirements for starting a business vary by state or country?",
    "How do legal implications of bankruptcy affect personal assets and credit?",
    "How do legal frameworks govern environmental protection laws and regulations?",
    "How do legal rights of employees protect them from workplace discrimination?",
    "How do legal obligations of employers ensure fair labor practices and compliance with labor laws?",
    "How do legal processes for adopting a child from another country work?",
    "How do legal systems handle disputes over shared property in divorce cases?",
    "How do legal frameworks regulate the use of surveillance technology in law enforcement?",
    "How do legal procedures for appealing a court decision work?",
    "How do legal protections for consumers prevent deceptive practices and false advertising?",
    "How do legal requirements for registering a trademark or copyright protect intellectual property?",
    "How do legal implications of violating a restraining order affect personal freedom and safety?",
    "How do legal systems address issues of police misconduct and brutality?",
    "How do legal frameworks govern the use of drones for surveillance and privacy concerns?",
    "How do legal rights of prisoners protect them from mistreatment and ensure humane conditions?",
    "How do legal obligations of correctional facilities ensure compliance with human rights standards?",
    "How do legal procedures for filing a complaint against a law enforcement officer work?",
    "How do legal protections for victims of domestic violence ensure safety and support?",
    "How do legal systems handle cases of identity theft and financial fraud?",
    "How do legal frameworks regulate the use of facial recognition technology in public spaces?",
    "How do legal procedures for handling a child custody dispute work?",
    "How do legal rights of parents protect them in adoption proceedings?",
    "How do legal obligations of adoptive parents ensure post-adoption support and care?",
    "How do legal implications of violating family law regulations affect family relationships?",
    "How do legal systems address issues of human trafficking and modern slavery?",
    "How do legal frameworks govern the use of biometric data in law enforcement and security?",
    "How do legal rights of refugees protect them in asylum proceedings?",
    "How do legal obligations of governments ensure refugee rights and protections?",
    "How do legal procedures for filing a claim for workers' compensation work?",
    "How do legal protections for employees prevent workplace injuries and ensure safety?",
    "How do legal requirements for reporting child abuse or neglect work?",
    "How do legal systems handle cases of elder abuse or neglect?",
    "How do legal frameworks regulate the use of artificial intelligence in law enforcement and justice?",
    "How do legal procedures for contesting a will work?",
    "How do legal rights of beneficiaries protect them in trust disputes?",
    "How do legal obligations of trustees ensure proper trust administration and management?",
    "How do legal implications of violating securities laws affect investors and financial markets?",
    "How do legal systems address issues of insider trading or stock manipulation?",
  ],

  LEGAL_GROUNDS_AND_DISPUTES: [
    "What are the legal grounds for filing a lawsuit against a corporation for negligence?",
    "What are the legal grounds for contesting a will based on undue influence?",
    "What are the legal grounds for appealing a court decision regarding child custody?",
    "What are the legal grounds for seeking a restraining order against a stalker?",
    "What are the legal grounds for terminating a contract due to breach of terms?",
    "What are the legal grounds for filing a personal injury claim against a healthcare provider?",
    "What are the legal grounds for suing a government agency for misconduct?",
    "What are the legal grounds for contesting an eviction notice based on landlord negligence?",
    "What are the legal grounds for seeking spousal support or alimony in a divorce?",
    "What are the legal grounds for modifying a child custody agreement due to changed circumstances?",
    "What are the legal grounds for filing a complaint against a law enforcement officer for misconduct?",
    "What are the legal grounds for seeking whistleblower protection in a corporate setting?",
    "What are the legal grounds for filing a claim for wrongful termination due to discrimination?",
    "What are the legal grounds for contesting a traffic ticket based on procedural errors?",
    "What are the legal grounds for filing a lawsuit against a manufacturer for product liability?",
    "What are the legal grounds for contesting a zoning decision based on environmental concerns?",
    "What are the legal grounds for seeking an injunction against a competitor for unfair business practices?",
    "What are the legal grounds for filing a complaint against a financial institution for deceptive practices?",
    "What are the legal grounds for seeking compensation for property damage caused by negligence?",
    "What are the legal grounds for contesting a tax assessment or audit based on errors?",
    "What are the legal grounds for seeking a court order for child support modifications?",
    "What are the legal grounds for filing a complaint against a real estate agent for misrepresentation?",
    "What are the legal grounds for contesting a foreclosure proceeding based on procedural irregularities?",
    "What are the legal grounds for seeking compensation for loss of business income due to contractual breaches?",
    "What are the legal grounds for filing a lawsuit against a construction company for defects in workmanship?",
    "What are the legal grounds for contesting a denial of insurance benefits based on policy terms?",
    "What are the legal grounds for seeking compensation for personal injury from a defective product?",
    "What are the legal grounds for filing a complaint against a telecommunications provider for service disruptions?",
    "What are the legal grounds for contesting a traffic accident liability determination based on evidence?",
    "What are the legal grounds for seeking compensation for environmental damage caused by negligence?",
    "What are the legal grounds for filing a lawsuit against a pharmaceutical company for harm caused by a medication?",
    "What are the legal grounds for contesting a denial of unemployment benefits based on eligibility criteria?",
    "What are the legal grounds for seeking compensation for loss of consortium or companionship due to wrongful death?",
    "What are the legal grounds for filing a complaint against a healthcare provider for lack of informed consent?",
    "What are the legal grounds for contesting a decision regarding veterans' education benefits based on eligibility?",
    "What are the legal grounds for seeking compensation for harm caused by a defective medical treatment or procedure?",
    "What are the legal grounds for filing a lawsuit against a construction company for construction defects?",
    "What are the legal grounds for contesting a decision regarding child support modifications based on changed circumstances?",
    "What are the legal grounds for seeking compensation for loss of business due to government actions or regulations?",
    "What are the legal grounds for filing a complaint against a real estate developer for misrepresentation or fraud?",
    "What are the legal grounds for contesting a decision regarding SSI or disability benefits based on medical evidence?",
    "What are the legal grounds for seeking compensation for harm caused by a defective product used in a workplace setting?",
    "What are the legal grounds for filing a lawsuit against a company for violating employment laws or labor regulations?",
    "What are the legal grounds for contesting a decision regarding Medicaid expansion or eligibility based on income criteria?",
    "What are the legal grounds for seeking compensation for loss of use of a vehicle due to a defective part or manufacturing flaw?",
    "What are the legal grounds for filing a complaint against a financial institution for predatory lending practices or usury?",
    "What are the legal grounds for contesting a decision regarding veterans' pension benefits based on service records?",
    "What are the legal grounds for seeking compensation for harm caused by exposure to hazardous materials or toxic substances?",
    "What are the legal grounds for filing a lawsuit against a company for violating consumer protection laws or deceptive trade practices?",
    "What are the legal grounds for contesting a decision regarding housing discrimination claims based on protected classes?",
  ],
};